version: 2.1

orbs:
  python: circleci/python@2.0

jobs:
  build: 
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages
      - run: | 
          python -m pytest --version
          mkdir workspace
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - ~/working

  test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - attach_workspace:
          at: workspace
      - checkout
      - run:
          name: Run tests
          command: python -m pytest --junitxml=test-results.xml --cov
      - store_test_results:
          path: test-results.xml

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build