version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  test:
    machine: true
    resource_class: large
    parallelism: 1
    steps:
      - checkout
      - run: python3 -m pip install -r requirements.txt 
      - run:
          name: Run tests
          command: |
            python3 -m pytest tests/test_calculator.py -v --no-header
      - store_test_results:
          path: test-results.xml

workflows:
  build-and-test:
    jobs:
      - test
