version: 2.1

orbs:
  python: circleci/python@2.0.0

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Run tests
          command: python -m pytest --junitxml=test-results.xml --cov

workflows:
  sample:
    jobs:
      - build-and-test
