version: 2.1

jobs:
  test:
    docker: 
      - image: cimg/python:3.10
    parallelism: q
    steps:
      - checkout
      - run: python3 -m pip install -r requirements.txt 
      - run:
          name: Run tests
          command: |
            TEST_FILES=$(circleci tests glob "**/tests/*.py" | circleci tests split --split-by=timings)
            python3 -m pytest $TEST_FILES --junitxml=test-results.xml --cov
      - store_test_results:
          path: test-results.xml

workflows:
  build-and-test:
    jobs:
      - test
