version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10.2
    #resource_class: logan/container-runner
    parallelism: 2
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys: 
            - dev1-{{checksum "requirements.txt"}}
            - dev1-
      - run: pip install -r requirements.txt 
      - run:
          name: Run tests
          command: |
            TEST_FILES=$(circleci tests glob "**/tests/*.py")
            python -m pytest $TEST_FILES --junitxml=test-results.xml --cov
      - store_test_results:
          path: test-results.xml
      - save_cache:
          paths:
            - .
          key: dev1-{{checksum "requirements.txt"}}

workflows:
  build-and-test:
    jobs:
      - test
