version: 2.1

orbs:
  python: circleci/python@2.0

jobs:
  build: 
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages
  test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - run:
          name: Run tests
          command: python -m pytest --junitxml=test-results.xml --cov
      - store_test_results:
          path: test-results.xml
workflows:
  sample:
    jobs:
      - build
      - test